### ISSUE TITLE
Want to return all entries with cmdlet AppConfigurationKeyValue

### ISSUE THREAD

**Issue by jiwanovski87** [mieel/PSAzureAppConfiguration#4]
Hi,

when I call the cmdlet I want to have the possibility to retrieve every entry.
Currently I get only one entry as result. I get only one entry because it gets filtered by `Select-Object -First 1`.

In my case I want to get every entry for a given key where I do have different labels and the user needs to select one of the labels.. In this case values = labels. It's just an entry point... 

Thanks

**Comment by mieel** [comment]
Hi, can you give an example of your input?

If you want one key, specify the `-key` param. You can use a `*` wildcard to get more keys.

using `-key *` will give you all the keys, `-key develop*` will give you only the ones that start with `develop`.

use `-label *` if you want to get all labels for a key

**Comment by jiwanovski87** [comment]
Sure.

The "problem" is, that I do have a key multiple times.
`Get-AppConfigurationKeyValue -Store "StoreName"-Key "TenantId" -Label '*'`

I do have a multi tenant system and I am writing a script which should prompt me first, which tenants are available.
For this I want to get all Keys "TenantId". After this I am storing the config values for each tenant and the tenant id is the label. 

I would prefer to remove the part `Select-Object -First 1`. In normal case I will only get one result from the cmdlet `Get-AppConfigurationKeyValue`. But in a few cases I believe you will get more than one result and if so, the user should add code to determine what to do with the array. The cmdlet `Get-AppConfigurationKeyValue` cannot know what to do with that.

Example what is stored in app config
| Key        | Value           | Label  |
| ------------- |:-------------:| -----:|
| TenantId      | TenantA | TenantA |
| TenantId      | TenantB      |   TenantB |
| DatabaseName | DatabaseNameA      |    TenantA |
| DatabaseName | DatabaseNameB      |    TenantB |

**Comment by mieel** [comment]
If you do this ‘Get-AppConfigurationKeyValue -Store "StoreName"-Key "TenantId" -Label '*' | Select-Object -Property Label’ you would get a list of your labels of that key.

The cmdlet  just retrieves keys, any other logic should be done outside of it.

**Comment by jiwanovski87** [comment]
I'm sorry but this seems not to work.. 
I do not get a list of labels back... Just the firstone... 

Am I doing something wrong?
`$tenantIdList = Get-AppConfigurationKeyValue -Store $AppConfigName -Key TenantId -Label '*'  | Select-Object -Property Label
write-host $tenantIdList.count`

I only get a lenght of 1...

**Comment by mieel** [comment]
Hey I finally got a decent amount of time to look into it.
I think I got what you mean.
I released a new version, can you try again with the patch?
https://github.com/mieel/PSAzureAppConfiguration/releases/tag/0.1.3

**Comment by jiwanovski87** [comment]
I have tried, but now the count returns zero.

I believe the problem now is that `$Output` never gets filled when `$Label = '*'`.

**Comment by mieel** [comment]
You are right, can you try again? (v.0.1.4)
Im sorry for not properly testing is, it's been a while since I worked on this project, and I don't have a working instance to test wht.

**Comment by jiwanovski87** [comment]
Yes now it's working for me. 
Thanks!
